development:
  adapter: postgresql
  encoding: utf8
  database: coffeecompany
  username: JFP
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: coffeecompany
  username: JFP
  password: 